from django.utils.translation import gettext_lazy as _
# Generated by Django 6.0.5 on 2026-06-09 23:30

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_('ID'))),
                ('clinic_name', models.CharField(default='CareFlow Clinic', max_length=200)),
                ('clinic_address', models.TextField(blank=True, default='Clinic Address')),
                ('clinic_phone', models.CharField(blank=True, default='+123456789', max_length=20)),
                ('clinic_email', models.EmailField(blank=True, default='info@clinic.com', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/')),
                ('working_days', models.JSONField(blank=True, default=list)),
                ('opening_time', models.TimeField(default=datetime.time(9, 0))),
                ('closing_time', models.TimeField(default=datetime.time(17, 0))),
                ('default_slot_duration', models.PositiveIntegerField(default=30)),
                ('currency', models.CharField(default='EGP', max_length=10)),
            ],
            options={
                'verbose_name': 'Clinic Settings',
                'verbose_name_plural': 'Clinic Settings',
            },
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_('ID'))),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-heart-pulse', max_length=50)),
                ('price_range', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('doctors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'DOCTOR'}, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinic Service',
                'verbose_name_plural': 'Clinic Services',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
